# Generated by Django 4.0.1 on 2022-03-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
            ],
        ),
    ]
