# Generated by Django 4.0.1 on 2022-03-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_customerwiseproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerwiseproduct',
            old_name='c_id',
            new_name='c_name',
        ),
    ]
