# Generated by Django 4.0.1 on 2022-03-12 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_p_id_customerwiseproduct_pc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwiseproduct',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
