# Generated by Django 4.0.1 on 2022-03-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_customerwiseproduct_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerwiseproduct',
            old_name='pname',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='customerwiseproduct',
            old_name='pprice',
            new_name='p_price',
        ),
    ]
