# Generated by Django 4.0.1 on 2022-03-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_rename_pname_customerwiseproduct_p_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwiseproduct',
            name='p_name',
            field=models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
