# Generated by Django 4.0.1 on 2022-03-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_customerwiseproduct_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerwiseproduct',
            name='p_name',
        ),
        migrations.AddField(
            model_name='customerwiseproduct',
            name='p_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
