# Generated by Django 4.0.1 on 2022-03-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('delivery Boy', 'DeliveryBoy')], max_length=20),
        ),
    ]
